# docker-compose.yml
version: "3"
services:
  app:
    container_name: blog-backend
    build: .
    volumes:
      - . :/usr/src/app/server
    command: npm start
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
